# -*- coding: utf-8 -*-
"""driver drowsiness final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aPSEATrjiBcc6_8qyINMnCvj_QUIh5il
"""

# ═══════════════════════════════════════════════════════════════════════════
# STEP 1: MOUNT GOOGLE DRIVE
# ═══════════════════════════════════════════════════════════════════════════
from google.colab import drive
drive.mount('/content/drive')

!pip uninstall -y numpy
!pip install numpy==1.26.4

!pip install -q tensorflow-model-optimization

# ═══════════════════════════════════════════════════════════════════════════
# STEP 2: INSTALL DEPENDENCIES
# ═══════════════════════════════════════════════════════════════════════════
# Fix: split thành 2 lệnh riêng biệt
# !pip uninstall -y numpy
# !pip install numpy==1.26.4
# !pip install -q tensorflow-model-optimization

# Chạy các lệnh trên trong cell riêng trước khi chạy script này
# Sau đó RESTART RUNTIME rồi chạy từ đây

import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

print(f"TensorFlow version: {tf.__version__}")
print(f"GPU: {tf.config.list_physical_devices('GPU')}")

# ── Import tfmot sau khi đã cài ──────────────────────────────────────────
try:
    import tensorflow_model_optimization as tfmot
    QAT_AVAILABLE = True
    print("✅ tensorflow-model-optimization ready")
except ImportError:
    QAT_AVAILABLE = False
    print("⚠️  QAT không khả dụng — sẽ dùng PTQ thay thế")

# ═══════════════════════════════════════════════════════════════════════════
# STEP 3: LOAD & VERIFY ASIC DATA
# ═══════════════════════════════════════════════════════════════════════════
DRIVE_PATH  = '/content/drive/MyDrive/Colab Notebooks/DriverDrowsiness/PreprocessedData_ASIC'
OUTPUT_PATH = '/content/drive/MyDrive/Colab Notebooks/DriverDrowsiness/Models'
os.makedirs(OUTPUT_PATH, exist_ok=True)

SCALE_FACTOR = 128.0
IMG_SIZE     = 128
BATCH_SIZE   = 32

def load_asic_data(drive_path=DRIVE_PATH):
    print("=" * 70)
    print("LOADING ASIC-OPTIMIZED DATA")
    print("=" * 70)

    files = {
        'X_train': os.path.join(drive_path, 'X_train_asic.npy'),
        'X_test':  os.path.join(drive_path, 'X_test_asic.npy'),
        'y_train': os.path.join(drive_path, 'y_train_asic.npy'),
        'y_test':  os.path.join(drive_path, 'y_test_asic.npy'),
    }
    for name, path in files.items():
        if not os.path.exists(path):
            raise FileNotFoundError(f"❌ Không tìm thấy: {path}")
        print(f"  ✅ {name}: {path}")

    X_train = np.load(files['X_train'])
    X_test  = np.load(files['X_test'])
    y_train = np.load(files['y_train'])
    y_test  = np.load(files['y_test'])

    print(f"\n📊 Format gốc (Q0.7 int8):")
    print(f"  X_train: shape={X_train.shape}, dtype={X_train.dtype}, range=[{X_train.min()}, {X_train.max()}]")
    print(f"  X_test:  shape={X_test.shape}")
    print(f"  y_train: shape={y_train.shape}, classes={np.unique(y_train)}")

    assert X_train.dtype == np.int8, "❌ X_train phải là int8"
    assert X_train.shape[1] == IMG_SIZE and X_train.shape[2] == IMG_SIZE, \
        f"❌ Kích thước phải là {IMG_SIZE}x{IMG_SIZE}"
    assert (IMG_SIZE & (IMG_SIZE - 1)) == 0, "❌ IMG_SIZE phải là power-of-2"
    print(f"\n✅ Xác nhận ASIC format: int8, {IMG_SIZE}x{IMG_SIZE} (power-of-2)")

    print(f"\n🔄 Chuyển đổi: int8 / {SCALE_FACTOR:.0f} → float32")
    X_train_f = X_train.astype(np.float32) / SCALE_FACTOR
    X_test_f  = X_test.astype(np.float32)  / SCALE_FACTOR
    print(f"  X_train float32 range: [{X_train_f.min():.4f}, {X_train_f.max():.4f}]")

    X_train_f = np.expand_dims(X_train_f, axis=-1)
    X_test_f  = np.expand_dims(X_test_f,  axis=-1)

    print(f"\n📐 Shape sau khi thêm channel:")
    print(f"  X_train: {X_train_f.shape}")
    print(f"  X_test:  {X_test_f.shape}")

    for split_name, y in [('Train', y_train), ('Test', y_test)]:
        unique, counts = np.unique(y, return_counts=True)
        print(f"\n📊 {split_name} class distribution:")
        for cls, cnt in zip(unique, counts):
            label = "Fatigue (0)" if cls == 0 else "Active  (1)"
            print(f"  {label}: {cnt:4d}  ({100*cnt/len(y):.1f}%)")

    print("\n" + "=" * 70)
    print("✅ DATA READY")
    print("=" * 70)
    return X_train_f, X_test_f, y_train, y_test


X_train, X_test, y_train, y_test = load_asic_data()

# ═══════════════════════════════════════════════════════════════════════════
# STEP 4: DATA AUGMENTATION (tf.data pipeline)
# ═══════════════════════════════════════════════════════════════════════════
AUTOTUNE = tf.data.AUTOTUNE

def augment(image, label):
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_brightness(image, max_delta=0.1)
    image = tf.image.random_contrast(image, lower=0.9, upper=1.1)
    image = tf.clip_by_value(image, 0.0, 1.0)
    return image, label

train_dataset = (
    tf.data.Dataset.from_tensor_slices((X_train, y_train.astype(np.float32)))
    .shuffle(buffer_size=len(X_train), seed=42)
    .map(augment, num_parallel_calls=AUTOTUNE)
    .batch(BATCH_SIZE)
    .prefetch(AUTOTUNE)
)

test_dataset = (
    tf.data.Dataset.from_tensor_slices((X_test, y_test.astype(np.float32)))
    .batch(BATCH_SIZE)
    .prefetch(AUTOTUNE)
)

train_steps = len(X_train) // BATCH_SIZE
test_steps  = len(X_test)  // BATCH_SIZE

print(f"✅ tf.data pipeline ready")
print(f"  Train batches : {train_steps}")
print(f"  Test batches  : {test_steps}")

# ═══════════════════════════════════════════════════════════════════════════
# STEP 5: BUILD ASIC-FRIENDLY BASE MODEL
# ═══════════════════════════════════════════════════════════════════════════
def build_asic_model(input_shape=(IMG_SIZE, IMG_SIZE, 1)):
    inputs = tf.keras.Input(shape=input_shape, name="input_q07")

    # Block 1: 128×128 → 64×64
    x = tf.keras.layers.SeparableConv2D(32, 3, padding='same', use_bias=False, name='conv1')(inputs)
    x = tf.keras.layers.BatchNormalization(name='bn1')(x)
    x = tf.keras.layers.ReLU(name='relu1')(x)
    x = tf.keras.layers.MaxPooling2D(2, name='pool1')(x)

    # Block 2: 64×64 → 32×32
    x = tf.keras.layers.SeparableConv2D(64, 3, padding='same', use_bias=False, name='conv2')(x)
    x = tf.keras.layers.BatchNormalization(name='bn2')(x)
    x = tf.keras.layers.ReLU(name='relu2')(x)
    x = tf.keras.layers.MaxPooling2D(2, name='pool2')(x)

    # Block 3: 32×32 → 16×16
    x = tf.keras.layers.SeparableConv2D(128, 3, padding='same', use_bias=False, name='conv3')(x)
    x = tf.keras.layers.BatchNormalization(name='bn3')(x)
    x = tf.keras.layers.ReLU(name='relu3')(x)
    x = tf.keras.layers.MaxPooling2D(2, name='pool3')(x)

    # Block 4: 16×16 (deep features)
    x = tf.keras.layers.SeparableConv2D(128, 3, padding='same', use_bias=False, name='conv4')(x)
    x = tf.keras.layers.BatchNormalization(name='bn4')(x)
    x = tf.keras.layers.ReLU(name='relu4')(x)

    # Head
    x = tf.keras.layers.GlobalAveragePooling2D(name='gap')(x)
    x = tf.keras.layers.Dense(32, use_bias=True, name='fc1')(x)
    x = tf.keras.layers.ReLU(name='relu_fc')(x)
    x = tf.keras.layers.Dense(1, use_bias=True, name='output')(x)

    model = tf.keras.Model(inputs, x, name="drowsiness_asic")
    return model


base_model = build_asic_model()

print("=" * 70)
print("ASIC MODEL ARCHITECTURE")
print("=" * 70)
base_model.summary()

total_params = base_model.count_params()
print(f"\n📊 ASIC Resource Estimate:")
print(f"  Total parameters : {total_params:,}")
print(f"  Weight memory    : {total_params/1024:.1f} KB (int8 sau quantize)")

# ═══════════════════════════════════════════════════════════════════════════
# STEP 6: TRAIN BASE MODEL (FLOAT32)
# ═══════════════════════════════════════════════════════════════════════════
print("=" * 70)
print("STEP 6: TRAINING BASE FLOAT32 MODEL")
print("=" * 70)

BASE_EPOCHS = 30

# Fix: dùng legacy optimizer để tương thích với tf.keras callbacks
base_model.compile(
    optimizer=tf.keras.optimizers.legacy.Adam(learning_rate=1e-3),
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
    metrics=['accuracy']
)

callbacks_base = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_accuracy',
        patience=7,
        restore_best_weights=True,
        verbose=1
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=3,
        min_lr=1e-6,
        verbose=1
    ),
]

print(f"Training {BASE_EPOCHS} epochs (với early stopping)...\n")

history_base = base_model.fit(
    train_dataset,
    epochs=BASE_EPOCHS,
    validation_data=test_dataset,
    steps_per_epoch=train_steps,
    validation_steps=test_steps,
    callbacks=callbacks_base,
    verbose=1
)

base_loss, base_acc = base_model.evaluate(X_test, y_test, verbose=0)
print(f"\n✅ Base model (float32) accuracy: {base_acc*100:.2f}%")

base_weights_path = os.path.join(OUTPUT_PATH, 'base_weights.weights.h5')
base_model.save_weights(base_weights_path)
print(f"💾 Weights saved: {base_weights_path}")

# ═══════════════════════════════════════════════════════════════════════════
# STEP 7: QUANTIZATION-AWARE TRAINING (QAT)
# ═══════════════════════════════════════════════════════════════════════════
# Fix: KHÔNG set TF_USE_LEGACY_KERAS (phá vỡ Keras 3)
# Fix: KHÔNG clone_model rồi set_weights từ chính nó (weights bị reset)
# Fix: tfmot.quantization.keras.quantize_model hoạt động trực tiếp với model

print("=" * 70)
print("STEP 7: QUANTIZATION-AWARE TRAINING (QAT)")
print("=" * 70)

QAT_EPOCHS = 15

if QAT_AVAILABLE:
    # Fix: Lưu weights ra file trước, wrap QAT, rồi load lại
    # (tránh lỗi khi tfmot thay đổi graph structure)
    _tmp_weights = os.path.join(OUTPUT_PATH, '_tmp_base.weights.h5')
    base_model.save_weights(_tmp_weights)

    # Wrap model với fake-quantization nodes
    quantize_model_fn = tfmot.quantization.keras.quantize_model
    qat_model = quantize_model_fn(base_model)

    # Load lại weights vào qat_model
    # Fix: dùng by_name=True + skip_mismatch=True vì QAT thêm extra variables
    qat_model.load_weights(_tmp_weights, by_name=True, skip_mismatch=True)

    qat_model.compile(
        optimizer=tf.keras.optimizers.legacy.Adam(learning_rate=1e-4),
        loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
        metrics=['accuracy']
    )

    print("📊 QAT model (với fake-quant nodes):")
    qat_model.summary()

    print(f"\n🔧 Fine-tuning QAT ({QAT_EPOCHS} epochs)...\n")

    callbacks_qat = [
        tf.keras.callbacks.EarlyStopping(
            monitor='val_accuracy',
            patience=5,
            restore_best_weights=True,
            verbose=1
        ),
    ]

    history_qat = qat_model.fit(
        train_dataset,
        epochs=QAT_EPOCHS,
        validation_data=test_dataset,
        steps_per_epoch=train_steps,
        validation_steps=test_steps,
        callbacks=callbacks_qat,
        verbose=1
    )

    qat_loss, qat_acc = qat_model.evaluate(X_test, y_test, verbose=0)
    print(f"\n✅ QAT model accuracy : {qat_acc*100:.2f}%")
    print(f"   Base model accuracy: {base_acc*100:.2f}%")
    print(f"   QAT accuracy drop  : {(base_acc - qat_acc)*100:.2f}%  (target: < 1%)")

    qat_weights_path = os.path.join(OUTPUT_PATH, 'qat_weights.weights.h5')
    qat_model.save_weights(qat_weights_path)
    print(f"💾 QAT weights saved: {qat_weights_path}")

    model_to_export = qat_model
    history_final   = history_qat

else:
    print("⚠️  QAT không khả dụng → dùng PTQ (accuracy drop có thể cao hơn)")
    model_to_export = base_model
    history_final   = history_base
    qat_acc         = base_acc

# ═══════════════════════════════════════════════════════════════════════════
# STEP 8: EXPORT INT8 TFLITE
# ═══════════════════════════════════════════════════════════════════════════
print("=" * 70)
print("STEP 8: EXPORT INT8 TFLITE (ASIC-READY)")
print("=" * 70)

converter = tf.lite.TFLiteConverter.from_keras_model(model_to_export)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# Fix: representative_dataset phải yield list of numpy arrays
# Giới hạn 200 mẫu để tránh timeout
N_CALIB = min(200, len(X_train))

def representative_dataset():
    for i in range(N_CALIB):
        sample = X_train[i:i+1].astype(np.float32)
        yield [sample]

converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type      = tf.int8
converter.inference_output_type     = tf.int8

print("Converting to INT8 TFLite... (có thể mất vài phút)")
tflite_model = converter.convert()

tflite_path = os.path.join(OUTPUT_PATH, 'drowsiness_asic_int8.tflite')
with open(tflite_path, 'wb') as f:
    f.write(tflite_model)

print(f"\n✅ INT8 TFLite saved: {tflite_path}")
print(f"   Model size: {len(tflite_model)/1024:.1f} KB")

# ═══════════════════════════════════════════════════════════════════════════
# STEP 9: VERIFY INT8 ACCURACY + SCALE FACTORS
# ═══════════════════════════════════════════════════════════════════════════
print("=" * 70)
print("STEP 9: VERIFY INT8 MODEL + SCALE FACTORS")
print("=" * 70)

interpreter = tf.lite.Interpreter(model_path=tflite_path)
interpreter.allocate_tensors()

input_details  = interpreter.get_input_details()
output_details = interpreter.get_output_details()

inp_detail = input_details[0]
inp_scale  = float(inp_detail['quantization_parameters']['scales'][0])
inp_zp     = int(inp_detail['quantization_parameters']['zero_points'][0])

print(f"\n📥 Input tensor:")
print(f"   Shape      : {inp_detail['shape']}")
print(f"   Dtype      : {inp_detail['dtype']}")
print(f"   Scale      : {inp_scale:.8f}")
print(f"   Zero point : {inp_zp}")

print(f"\n🔢 Quantization details:")
print(f"{'Index':>5}  {'Name':<45}  {'Dtype':<8}  {'Scale / Info'}")
print("-" * 90)

all_details = interpreter.get_tensor_details()
for t in all_details:
    qp = t['quantization_parameters']
    if len(qp['scales']) == 0:
        continue
    scales = qp['scales']
    zps    = qp['zero_points']
    if len(scales) == 1:
        scale_str = f"scale={scales[0]:.8f}, zp={zps[0]}"
    else:
        scale_str = f"per-channel {len(scales)} ch, scale[0]={scales[0]:.8f}"
    print(f"{t['index']:>5}  {t['name']:<45}  {str(t['dtype']):<8}  {scale_str}")

# Accuracy evaluation
print(f"\n📊 Đánh giá accuracy INT8 model...")
N_EVAL = min(len(X_test), 500)
correct = 0

out_zp = int(output_details[0]['quantization_parameters']['zero_points'][0])

for i in range(N_EVAL):
    sample = X_test[i:i+1].astype(np.float32)
    sample_int8 = np.round(sample / inp_scale + inp_zp).clip(-128, 127).astype(np.int8)

    interpreter.set_tensor(input_details[0]['index'], sample_int8)
    interpreter.invoke()
    output = interpreter.get_tensor(output_details[0]['index'])

    pred = 1 if int(output[0][0]) > out_zp else 0
    if pred == y_test[i]:
        correct += 1

int8_acc = correct / N_EVAL * 100

print(f"\n{'Model':<30} {'Accuracy':>10}")
print("-" * 42)
print(f"{'Float32 base model':<30} {base_acc*100:>9.2f}%")
if QAT_AVAILABLE:
    print(f"{'QAT model (fake-quant)':<30} {qat_acc*100:>9.2f}%")
print(f"{'INT8 TFLite (ASIC target)':<30} {int8_acc:>9.2f}%")
print(f"{'Accuracy drop vs float32':<30} {(base_acc*100 - int8_acc):>+9.2f}%")

if base_acc*100 - int8_acc < 2.0:
    print(f"\n✅ Accuracy drop < 2% — ĐẠT yêu cầu ASIC deployment")
else:
    print(f"\n⚠️  Accuracy drop > 2% — Xem xét tăng QAT epochs hoặc kiểm tra data")

# ═══════════════════════════════════════════════════════════════════════════
# STEP 10: EXTRACT WEIGHTS FOR ASIC (C Header)
# ═══════════════════════════════════════════════════════════════════════════
def extract_weights_for_asic(tflite_path, output_dir):
    interp = tf.lite.Interpreter(model_path=tflite_path)
    interp.allocate_tensors()

    lines = [
        "// ============================================================",
        "// AUTO-GENERATED — ASIC Weight File",
        f"// Source: {os.path.basename(tflite_path)}",
        "// ============================================================",
        "",
        "#ifndef ASIC_WEIGHTS_H",
        "#define ASIC_WEIGHTS_H",
        "",
        "#include <stdint.h>",
        "",
    ]

    for t in interp.get_tensor_details():
        qp = t["quantization_parameters"]
        try:
            data = interp.get_tensor(t["index"])
        except Exception:
            continue

        if data is None:
            continue

        safe_name = (
            t["name"]
            .replace("/", "_")
            .replace(":", "_")
            .replace(".", "_")
        )

        if data.dtype == np.int8 and len(qp["scales"]) > 0:
            flat = data.flatten()
            data_str = ", ".join(str(int(v)) for v in flat)
            lines += [
                f"// Tensor index {t['index']}, shape = {data.shape}",
                f"const int8_t {safe_name}[{len(flat)}] = {{",
                f"    {data_str}",
                "};",
                "",
            ]
            scales = qp["scales"]
            scales_str = ", ".join(f"{s:.10f}f" for s in scales)
            lines += [
                f"const float {safe_name}_scale[{len(scales)}] = {{",
                f"    {scales_str}",
                "};",
                "",
            ]

        elif data.dtype == np.int32:
            flat = data.flatten()
            data_str = ", ".join(str(int(v)) for v in flat)
            lines += [
                f"// Bias tensor index {t['index']}, shape = {data.shape}",
                f"const int32_t {safe_name}[{len(flat)}] = {{",
                f"    {data_str}",
                "};",
                "",
            ]

    lines.append("#endif  // ASIC_WEIGHTS_H")

    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "asic_weights.h")
    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"✅ ASIC header generated: {output_path}")
    return output_path

extract_weights_for_asic(tflite_path, OUTPUT_PATH)

# ═══════════════════════════════════════════════════════════════════════════
# STEP 11: TRAINING REPORT + BIỂU ĐỒ
# ═══════════════════════════════════════════════════════════════════════════
print("=" * 70)
print("STEP 11: TRAINING REPORT")
print("=" * 70)

print("\n📋 Layer-by-layer architecture:")
print(f"{'#':<3}  {'Layer':<30}  {'Output shape':<20}  {'Params':>8}")
print("-" * 70)
for idx, layer in enumerate(base_model.layers):
    try:
        out_shape = str(layer.output_shape[1:])
    except Exception:
        out_shape = "N/A"
    n_params = layer.count_params()
    print(f"{idx:<3}  {layer.name:<30}  {out_shape:<20}  {n_params:>8,}")

def last(hist, key):
    return hist.history[key][-1]

print(f"\n{'─'*50}")
print(f"FINAL RESULTS SUMMARY")
print(f"{'─'*50}")

print(f"\n[Base Model — Float32]")
print(f"  Train accuracy : {last(history_base,'accuracy')*100:.2f}%")
print(f"  Val accuracy   : {last(history_base,'val_accuracy')*100:.2f}%")

if QAT_AVAILABLE:
    print(f"\n[QAT Model — Fake-Quant]")
    print(f"  Train accuracy : {last(history_qat,'accuracy')*100:.2f}%")
    print(f"  Val accuracy   : {last(history_qat,'val_accuracy')*100:.2f}%")

print(f"\n[INT8 TFLite — ASIC Target]")
print(f"  INT8 accuracy  : {int8_acc:.2f}%")
print(f"  Model size     : {len(tflite_model)/1024:.1f} KB")

# Biểu đồ
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("ASIC Driver Drowsiness — Training History", fontsize=14)

ax = axes[0]
ax.plot(history_base.history['accuracy'],     label='Base Train', color='steelblue')
ax.plot(history_base.history['val_accuracy'], label='Base Val',   color='steelblue', linestyle='--')
if QAT_AVAILABLE:
    offset = len(history_base.history['accuracy'])
    epochs_qat = range(offset, offset + len(history_qat.history['accuracy']))
    ax.plot(epochs_qat, history_qat.history['accuracy'],     label='QAT Train', color='darkorange')
    ax.plot(epochs_qat, history_qat.history['val_accuracy'], label='QAT Val',   color='darkorange', linestyle='--')
    ax.axvline(x=offset, color='gray', linestyle=':', alpha=0.7, label='QAT start')
ax.axhline(y=int8_acc/100, color='green', linestyle=':', alpha=0.8, label=f'INT8 ({int8_acc:.1f}%)')
ax.set_xlabel('Epoch'); ax.set_ylabel('Accuracy')
ax.set_title('Accuracy (Base → QAT → INT8)')
ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

ax = axes[1]
ax.plot(history_base.history['loss'],     label='Base Train', color='steelblue')
ax.plot(history_base.history['val_loss'], label='Base Val',   color='steelblue', linestyle='--')
if QAT_AVAILABLE:
    ax.plot(epochs_qat, history_qat.history['loss'],     label='QAT Train', color='darkorange')
    ax.plot(epochs_qat, history_qat.history['val_loss'], label='QAT Val',   color='darkorange', linestyle='--')
    ax.axvline(x=offset, color='gray', linestyle=':', alpha=0.7, label='QAT start')
ax.set_xlabel('Epoch'); ax.set_ylabel('Loss')
ax.set_title('Loss (Base → QAT)')
ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_PATH, 'training_history.png'), dpi=150)
plt.show()
print("📊 Biểu đồ đã lưu: training_history.png")

print("\n" + "=" * 70)
print("✅ COMPLETE QAT PIPELINE HOÀN THÀNH!")
print("=" * 70)
print(f"📁 Output files: {OUTPUT_PATH}")
print(f"  • base_weights.weights.h5")
if QAT_AVAILABLE:
    print(f"  • qat_weights.weights.h5")
print(f"  • drowsiness_asic_int8.tflite")
print(f"  • asic_weights.h")
print(f"  • training_history.png")