# -*- coding: utf-8 -*-
"""CNN Driver Drowsiness Model - ASIC - ChiThang

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aPSEATrjiBcc6_8qyINMnCvj_QUIh5il
"""

# ═══════════════════════════════════════════════════════════════════════════
# STEP 1: MOUNT GOOGLE DRIVE
# ═══════════════════════════════════════════════════════════════════════════
from google.colab import drive
drive.mount('/content/drive')

!pip uninstall -y numpy
!pip install numpy==1.26.4

!pip install -q tensorflow-model-optimization

# ═══════════════════════════════════════════════════════════════════════════
# STEP 2: INSTALL DEPENDENCIES
# ═══════════════════════════════════════════════════════════════════════════
# Fix: split thành 2 lệnh riêng biệt
# !pip uninstall -y numpy
# !pip install numpy==1.26.4
# !pip install -q tensorflow-model-optimization

# Chạy các lệnh trên trong cell riêng trước khi chạy script này
# Sau đó RESTART RUNTIME rồi chạy từ đây

import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

print(f"TensorFlow version: {tf.__version__}")
print(f"GPU: {tf.config.list_physical_devices('GPU')}")

# ── Import tfmot sau khi đã cài ──────────────────────────────────────────
try:
    import tensorflow_model_optimization as tfmot
    QAT_AVAILABLE = True
    print("✅ tensorflow-model-optimization ready")
except ImportError:
    QAT_AVAILABLE = False
    print("⚠️  QAT không khả dụng — sẽ dùng PTQ thay thế")

# ═══════════════════════════════════════════════════════════════════════════
# STEP 3: LOAD & VERIFY ASIC DATA
# ═══════════════════════════════════════════════════════════════════════════
DRIVE_PATH  = '/content/drive/MyDrive/Colab Notebooks/DriverDrowsiness/PreprocessedData_ASIC'
OUTPUT_PATH = '/content/drive/MyDrive/Colab Notebooks/DriverDrowsiness/Models'
os.makedirs(OUTPUT_PATH, exist_ok=True)

SCALE_FACTOR = 128.0
IMG_SIZE     = 64
BATCH_SIZE   = 32

def load_asic_data(drive_path=DRIVE_PATH):
    print("=" * 70)
    print("LOADING ASIC-OPTIMIZED DATA")
    print("=" * 70)

    files = {
        'X_train': os.path.join(drive_path, 'X_train_asic.npy'),
        'X_test':  os.path.join(drive_path, 'X_test_asic.npy'),
        'y_train': os.path.join(drive_path, 'y_train_asic.npy'),
        'y_test':  os.path.join(drive_path, 'y_test_asic.npy'),
    }
    for name, path in files.items():
        if not os.path.exists(path):
            raise FileNotFoundError(f"❌ Không tìm thấy: {path}")
        print(f"  ✅ {name}: {path}")

    X_train = np.load(files['X_train'])
    X_test  = np.load(files['X_test'])
    y_train = np.load(files['y_train'])
    y_test  = np.load(files['y_test'])

    print(f"\n📊 Format gốc (Q0.7 int8):")
    print(f"  X_train: shape={X_train.shape}, dtype={X_train.dtype}, range=[{X_train.min()}, {X_train.max()}]")
    print(f"  X_test:  shape={X_test.shape}")
    print(f"  y_train: shape={y_train.shape}, classes={np.unique(y_train)}")

    assert X_train.dtype == np.int8, "❌ X_train phải là int8"
    assert X_train.shape[1] == IMG_SIZE and X_train.shape[2] == IMG_SIZE, \
        f"❌ Kích thước phải là {IMG_SIZE}x{IMG_SIZE}"
    assert (IMG_SIZE & (IMG_SIZE - 1)) == 0, "❌ IMG_SIZE phải là power-of-2"
    print(f"\n✅ Xác nhận ASIC format: int8, {IMG_SIZE}x{IMG_SIZE} (power-of-2)")

    print(f"\n🔄 Chuyển đổi: int8 / {SCALE_FACTOR:.0f} → float32")
    X_train_f = X_train.astype(np.float32) / SCALE_FACTOR
    X_test_f  = X_test.astype(np.float32)  / SCALE_FACTOR
    print(f"  X_train float32 range: [{X_train_f.min():.4f}, {X_train_f.max():.4f}]")

    X_train_f = np.expand_dims(X_train_f, axis=-1)
    X_test_f  = np.expand_dims(X_test_f,  axis=-1)

    print(f"\n📐 Shape sau khi thêm channel:")
    print(f"  X_train: {X_train_f.shape}")
    print(f"  X_test:  {X_test_f.shape}")

    for split_name, y in [('Train', y_train), ('Test', y_test)]:
        unique, counts = np.unique(y, return_counts=True)
        print(f"\n📊 {split_name} class distribution:")
        for cls, cnt in zip(unique, counts):
            label = "Fatigue (0)" if cls == 0 else "Active  (1)"
            print(f"  {label}: {cnt:4d}  ({100*cnt/len(y):.1f}%)")

    print("\n" + "=" * 70)
    print("✅ DATA READY")
    print("=" * 70)
    return X_train_f, X_test_f, y_train, y_test


X_train, X_test, y_train, y_test = load_asic_data()

# ═══════════════════════════════════════════════════════════════════════════
# STEP 4: DATA AUGMENTATION (tf.data pipeline)
# ═══════════════════════════════════════════════════════════════════════════
# FIX: Bỏ random_brightness và random_contrast vì data đã ở dạng Q0.7
# (int8/128) — brightness/contrast shift làm lệch distribution so với
# calibration set, gây accuracy drop sau quantization.
# Chỉ giữ flip + noise nhẹ để augment mà không thay đổi scale.
AUTOTUNE = tf.data.AUTOTUNE

def augment(image, label):
    # Flip ngang — safe với driver face data
    image = tf.image.random_flip_left_right(image)
    # Gaussian noise rất nhỏ (std=0.01 ≈ 1.3 LSB ở int8) — simulate sensor noise
    # KHÔNG dùng brightness/contrast vì gây distribution shift với Q0.7 input
    noise = tf.random.normal(shape=tf.shape(image), mean=0.0, stddev=0.01)
    image = image + noise
    # Clip đúng range Q0.7: [-1.0, 1.0) tương ứng int8 [-128, 127] / 128
    image = tf.clip_by_value(image, -1.0, 1.0)
    return image, label

train_dataset = (
    tf.data.Dataset.from_tensor_slices((X_train, y_train.astype(np.float32)))
    .shuffle(buffer_size=len(X_train), seed=42)
    .map(augment, num_parallel_calls=AUTOTUNE)
    .batch(BATCH_SIZE)
    .prefetch(AUTOTUNE)
)

test_dataset = (
    tf.data.Dataset.from_tensor_slices((X_test, y_test.astype(np.float32)))
    .batch(BATCH_SIZE)
    .prefetch(AUTOTUNE)
)

# FIX: bỏ // để không bỏ sót batch cuối (drop_remainder=False mặc định)
# train_steps=None → Keras tự đếm toàn bộ batches
train_steps = None
test_steps  = None

print(f"✅ tf.data pipeline ready")
print(f"  Train samples : {len(X_train)}")
print(f"  Test samples  : {len(X_test)}")
print(f"  steps_per_epoch = None → Keras tự đếm toàn bộ batches")

#═════════════════════════════════════════════════════════════
# STEP 5 (SỬA LẠI): BUILD MODEL — fix BN range issue từ diagnostic
# ═══════════════════════════════════════════════════════════════════════════
#
# Vấn đề từ diagnostic:
#   - BN layers có range 17–25 → int8 resolution chỉ ~0.1/step → mất thông tin
#   - conv4_proj range 25.08 (worst), output range 23.16
#   - Weights OK (< 0.6), KHÔNG phải outlier weight
#
# Fix:
#   1. Đổi thứ tự: Conv → BN → ReLU6  (hiện tại: Conv → ReLU6 → BN cho một số layer)
#      ReLU6 clamp ở 6 → BN output bị giới hạn [-6, 6] → range giảm từ 25 xuống ~6
#   2. conv4_proj: thêm ReLU6 sau BN để clamp range
#   3. output layer: KHÔNG quantize → giữ float32, sigmoid tính ngoài

def build_asic_model(input_shape=(64, 64, 1)):
    inputs = tf.keras.Input(shape=input_shape, name="input_q07")

    # ===== Block 0: Quantize input (ignore in full precision) =====
    x = inputs  # chỉ giữ input layer

    # ===== Block 1 ===== (64 → 32)
    x = tf.keras.layers.DepthwiseConv2D(3, padding='same', use_bias=False, name='depthwise_conv1')(x)
    x = tf.keras.layers.Conv2D(32, 1, padding='same', use_bias=False, name='conv1')(x)
    x = tf.keras.layers.BatchNormalization(name='bn1')(x)
    x = tf.keras.layers.ReLU(max_value=6, name='relu1')(x)
    x = tf.keras.layers.MaxPooling2D(2, name='pool1')(x)

    # ===== Block 2 ===== (32 → 16)
    x = tf.keras.layers.DepthwiseConv2D(3, padding='same', use_bias=False, name='depthwise_conv2')(x)
    x = tf.keras.layers.Conv2D(64, 1, padding='same', use_bias=False, name='conv2')(x)
    x = tf.keras.layers.BatchNormalization(name='bn2')(x)
    x = tf.keras.layers.ReLU(max_value=6, name='relu2')(x)
    x = tf.keras.layers.MaxPooling2D(2, name='pool2')(x)

    # ===== Block 3 ===== (16 → 8)
    x = tf.keras.layers.DepthwiseConv2D(3, padding='same', use_bias=False, name='depthwise_conv3')(x)
    x = tf.keras.layers.Conv2D(128, 1, padding='same', use_bias=False, name='conv3')(x)
    x = tf.keras.layers.BatchNormalization(name='bn3')(x)
    x = tf.keras.layers.ReLU(max_value=6, name='relu3')(x)
    x = tf.keras.layers.MaxPooling2D(2, name='pool3')(x)

    # ===== Block 4 (Light Residual) =====
    # Skip branch
    skip = tf.keras.layers.Conv2D(128, 1, padding='same', use_bias=False, name='conv4_proj')(x)
    skip = tf.keras.layers.BatchNormalization(name='bn4_proj')(skip)

    # Main branch
    x = tf.keras.layers.DepthwiseConv2D(3, padding='same', use_bias=False, name='depthwise_conv4')(x)
    x = tf.keras.layers.Conv2D(128, 1, padding='same', use_bias=False, name='conv4')(x)
    x = tf.keras.layers.BatchNormalization(name='bn4')(x)
    x = tf.keras.layers.ReLU(max_value=6, name='relu4')(x)

    # Add skip connection
    x = tf.keras.layers.Add(name='skip_add')([x, skip])
    x = tf.keras.layers.ReLU(max_value=6, name='relu4b')(x)

    # ===== Head =====
    x = tf.keras.layers.GlobalAveragePooling2D(name='gap')(x)
    x = tf.keras.layers.Dense(64, use_bias=False, name='fc1')(x)
    x = tf.keras.layers.BatchNormalization(name='bn_fc1')(x)
    x = tf.keras.layers.ReLU(max_value=6, name='relu_fc1')(x)
    x = tf.keras.layers.Dropout(0.5, name='drop1')(x)
    outputs = tf.keras.layers.Dense(1, use_bias=True, name='output')(x)

    return tf.keras.Model(inputs, outputs, name="full_precision_model")

base_model = build_asic_model()

print("=" * 70)
print("ASIC MODEL ARCHITECTURE")
print("=" * 70)
base_model.summary()

total_params = base_model.count_params()
print(f"\n📊 ASIC Resource Estimate:")
print(f"  Total parameters : {total_params:,}")
print(f"  Weight memory    : {total_params/1024:.1f} KB (int8 sau quantize)")

# ═══════════════════════════════════════════════════════════════════════════
# STEP 6: TRAIN BASE MODEL (FLOAT32) — với fixes cho quantization
# ═══════════════════════════════════════════════════════════════════════════
print("=" * 70)
print("STEP 6: TRAINING BASE FLOAT32 MODEL")
print("=" * 70)

BASE_EPOCHS = 40  # FIX: tăng từ 30→40, EarlyStopping vẫn kiểm soát

base_model.compile(
    optimizer=tf.keras.optimizers.legacy.Adam(learning_rate=1e-3),
    # label_smoothing=0.05: model không overconfident → logit nhỏ hơn
    # → activation range hẹp → int8 quantize ít mất mát hơn
    loss=tf.keras.losses.BinaryCrossentropy(
        from_logits=True,
        label_smoothing=0.05
    ),
    metrics=['accuracy']
)

base_ckpt_path = os.path.join(OUTPUT_PATH, 'base_best.weights.h5')

callbacks_base = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_accuracy',
        patience=10,            # FIX: tăng patience để không dừng sớm
        restore_best_weights=True,
        verbose=1
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=4,             # FIX: tăng patience để LR không giảm quá sớm
        min_lr=1e-6,
        verbose=1
    ),
    # FIX: thêm ModelCheckpoint — backup an toàn hơn restore_best_weights
    # vì restore_best_weights đôi khi fail khi kết hợp với custom training loop
    tf.keras.callbacks.ModelCheckpoint(
        filepath=base_ckpt_path,
        monitor='val_accuracy',
        save_best_only=True,
        save_weights_only=True,
        verbose=1
    ),
]

print(f"Training {BASE_EPOCHS} epochs (với early stopping + checkpoint)...\n")

history_base = base_model.fit(
    train_dataset,
    epochs=BASE_EPOCHS,
    validation_data=test_dataset,
    steps_per_epoch=train_steps,   # None → dùng toàn bộ batches
    validation_steps=test_steps,   # None → dùng toàn bộ batches
    callbacks=callbacks_base,
    verbose=1
)

# Load best checkpoint để đảm bảo chắc chắn dùng weights tốt nhất
base_model.load_weights(base_ckpt_path)
base_loss, base_acc = base_model.evaluate(X_test, y_test, verbose=0)
print(f"\n✅ Base model (float32) accuracy: {base_acc*100:.2f}%")

if base_acc < 0.93:
    print(f"⚠️  WARNING: Base accuracy {base_acc*100:.2f}% < 93% target")
    print(f"   → Kiểm tra lại data quality hoặc tăng BASE_EPOCHS")
else:
    print(f"✅ Base accuracy đạt yêu cầu (>93%) — tiến hành QAT")

base_weights_path = os.path.join(OUTPUT_PATH, 'base_weights.weights.h5')
base_model.save_weights(base_weights_path)
print(f"💾 Weights saved: {base_weights_path}")

# ═══════════════════════════════════════════════════════════════════════════
# STEP 7: QUANTIZATION-AWARE TRAINING (QAT) — fixed
# ═══════════════════════════════════════════════════════════════════════════
print("=" * 70)
print("STEP 7: QUANTIZATION-AWARE TRAINING (QAT)")
print("=" * 70)

QAT_EPOCHS = 30

if QAT_AVAILABLE:
    _tmp_weights = os.path.join(OUTPUT_PATH, '_tmp_base.weights.h5')
    base_model.save_weights(_tmp_weights)

    # ── FIX QUAN TRỌNG: Exclude output layer khỏi QAT ─────────────────────
    # quantize_model() mặc định quantize TẤT CẢ layers kể cả Dense output.
    # Output layer là sigmoid logit (1 neuron) — quantize int8 tại đây gây
    # mất precision nghiêm trọng vì range rất nhỏ (~[-3, 3]).
    # Giải pháp: dùng quantize_annotate_layer để skip output layer.
    quantize_annotate_layer = tfmot.quantization.keras.quantize_annotate_layer
    quantize_annotate_model = tfmot.quantization.keras.quantize_annotate_model
    quantize_apply           = tfmot.quantization.keras.quantize_apply
    LastValueQuantizer       = tfmot.quantization.keras.quantizers.LastValueQuantizer
    MovingAverageQuantizer   = tfmot.quantization.keras.quantizers.MovingAverageQuantizer

    def apply_quantization_to_layer(layer):
        # Bỏ qua output Dense layer — giữ float32 để không mất precision
        if layer.name == 'output':
            return layer
        # Bỏ qua Dropout — không cần quantize, chỉ active khi train
        if isinstance(layer, tf.keras.layers.Dropout):
            return layer
        return quantize_annotate_layer(layer)

    # Clone model và annotate từng layer theo policy trên
    annotated_model = tf.keras.models.clone_model(
        base_model,
        clone_function=apply_quantization_to_layer,
    )

    # Apply QAT (thêm fake-quant nodes vào các layer được annotate)
    qat_model = quantize_apply(annotated_model)

    # Load weights từ base model đã train (by_name để map đúng dù có thêm nodes)
    qat_model.load_weights(_tmp_weights, by_name=True, skip_mismatch=True)

    # ── FIX: LR cho QAT ────────────────────────────────────────────────────
    # LR phải rất nhỏ: QAT chỉ fine-tune để adapter fake-quant noise,
    # KHÔNG re-learn weights. LR cao phá vỡ weights đã converge tốt.
    # 5e-5 → 2e-5: giảm thêm 2.5x so với bản cũ.
    #
    # FIX: Bỏ label_smoothing trong QAT.
    # label_smoothing làm mờ gradient signal — trong QAT ta cần gradient
    # rõ ràng để model học cách compensate quantization error.
    qat_model.compile(
        optimizer=tf.keras.optimizers.legacy.Adam(
            learning_rate=2e-5,       # FIX: giảm từ 5e-5 → 2e-5
            clipnorm=1.0              # FIX: gradient clipping, tránh spike
        ),
        loss=tf.keras.losses.BinaryCrossentropy(
            from_logits=True,
            label_smoothing=0.0       # FIX: bỏ label_smoothing trong QAT
        ),
        metrics=['accuracy']
    )

    print("📊 QAT model (với fake-quant nodes, output layer excluded):")
    qat_model.summary()

    qat_ckpt_path = os.path.join(OUTPUT_PATH, 'qat_best.weights.h5')

    print(f"\n🔧 Fine-tuning QAT ({QAT_EPOCHS} epochs)...\n")

    callbacks_qat = [
        tf.keras.callbacks.EarlyStopping(
            monitor='val_accuracy',
            patience=10,              # FIX: tăng patience, QAT converge chậm
            restore_best_weights=True,
            verbose=1
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor='val_loss',
            factor=0.5,
            patience=5,               # FIX: tăng patience
            min_lr=5e-8,              # FIX: min_lr nhỏ hơn để fine-tune cuối
            verbose=1
        ),
        # FIX: thêm checkpoint để đảm bảo luôn có best QAT weights
        tf.keras.callbacks.ModelCheckpoint(
            filepath=qat_ckpt_path,
            monitor='val_accuracy',
            save_best_only=True,
            save_weights_only=True,
            verbose=1
        ),
    ]

    history_qat = qat_model.fit(
        train_dataset,
        epochs=QAT_EPOCHS,
        validation_data=test_dataset,
        steps_per_epoch=train_steps,   # None → toàn bộ batches
        validation_steps=test_steps,   # None → toàn bộ batches
        callbacks=callbacks_qat,
        verbose=1
    )

    # Load best QAT checkpoint
    qat_model.load_weights(qat_ckpt_path)

    qat_loss, qat_acc = qat_model.evaluate(X_test, y_test, verbose=0)
    print(f"\n✅ QAT model accuracy : {qat_acc*100:.2f}%")
    print(f"   Base model accuracy: {base_acc*100:.2f}%")
    print(f"   QAT accuracy drop  : {(base_acc - qat_acc)*100:+.2f}%  (target: < 1%)")

    if qat_acc*100 < 93.0:
        print(f"⚠️  QAT accuracy {qat_acc*100:.2f}% < 93% — kiểm tra lại base accuracy")
    else:
        print(f"✅ QAT accuracy đạt target > 93%")

    qat_weights_path = os.path.join(OUTPUT_PATH, 'qat_weights.weights.h5')
    qat_model.save_weights(qat_weights_path)
    print(f"💾 QAT weights saved: {qat_weights_path}")

    model_to_export = qat_model
    history_final   = history_qat

else:
    print("⚠️  QAT không khả dụng → dùng PTQ")
    model_to_export = base_model
    history_final   = history_base
    qat_acc         = base_acc

# ═══════════════════════════════════════════════════════════════════════════
# STEP 8: EXPORT INT8 TFLITE — fixed
# ═══════════════════════════════════════════════════════════════════════════
print("=" * 70)
print("STEP 8: EXPORT INT8 TFLITE (ASIC-READY)")
print("=" * 70)

converter = tf.lite.TFLiteConverter.from_keras_model(model_to_export)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# Fix 5: tăng N_CALIB lên toàn bộ val set
# 200 mẫu thường không đủ để calibrate activation range chính xác
# Nguyên tắc: càng nhiều sample càng tốt, ít nhất 500-1000
N_CALIB = len(X_test)   # dùng toàn bộ test set làm calibration
print(f"📊 Calibration samples: {N_CALIB} (toàn bộ test set)")

def representative_dataset():
    # Fix 6: shuffle để đảm bảo diversity của calibration data
    idxs = np.random.permutation(N_CALIB)
    for i in idxs:
        sample = X_test[i:i+1].astype(np.float32)
        yield [sample]

converter.representative_dataset = representative_dataset

# Fix 7: thêm experimental_new_quantizer=True
# Dùng quantizer mới của TFLite, tốt hơn cho per-channel quantization
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type      = tf.int8
converter.inference_output_type     = tf.int8

# Fix 8: experimental options để giảm accuracy drop
converter._experimental_disable_per_channel = False  # BẬT per-channel (mặc định)

print("Converting to INT8 TFLite... (có thể mất vài phút)")
tflite_model = converter.convert()

tflite_path = os.path.join(OUTPUT_PATH, 'drowsiness_asic_int8.tflite')
with open(tflite_path, 'wb') as f:
    f.write(tflite_model)

print(f"\n✅ INT8 TFLite saved: {tflite_path}")
print(f"   Model size: {len(tflite_model)/1024:.1f} KB")

# ═══════════════════════════════════════════════════════════════════════════
# STEP 8.5: DIAGNOSTIC — tìm layer nào gây drop nhiều nhất
# ═══════════════════════════════════════════════════════════════════════════
print("=" * 70)
print("STEP 8.5: QUANTIZATION DIAGNOSTIC")
print("=" * 70)

# 1. Kiểm tra activation range của từng layer
# Range quá rộng → int8 không đủ resolution → accuracy drop
print("\n📊 Activation range per layer (dùng 100 mẫu):")
print(f"{'Layer':<40} {'Min':>10} {'Max':>10} {'Range':>10}")
print("-" * 72)

sample_batch = X_train[:100].astype(np.float32)

# Tạo model trung gian để lấy activation từng layer
activation_ranges = {}
for layer in base_model.layers:
    if not layer.weights:
        continue
    try:
        sub_model = tf.keras.Model(inputs=base_model.input, outputs=layer.output)
        acts = sub_model.predict(sample_batch, verbose=0)
        acts_flat = acts.flatten()
        act_min, act_max = acts_flat.min(), acts_flat.max()
        act_range = act_max - act_min
        activation_ranges[layer.name] = act_range
        # Cảnh báo range > 6 (ReLU6 sẽ clamp đúng, ReLU thường để range rất rộng)
        flag = " ⚠️  WIDE" if act_range > 10 else ""
        print(f"{layer.name:<40} {act_min:>10.4f} {act_max:>10.4f} {act_range:>10.4f}{flag}")
    except Exception:
        pass

# 2. Kiểm tra weight distribution
print(f"\n📊 Weight range per layer:")
print(f"{'Layer':<40} {'W_min':>10} {'W_max':>10} {'|W|_max':>10}")
print("-" * 72)
for layer in base_model.layers:
    if not layer.weights:
        continue
    for w in layer.weights:
        if 'kernel' in w.name:
            w_np = w.numpy().flatten()
            flag = " ⚠️  OUTLIER" if abs(w_np).max() > 3.0 else ""
            print(f"{layer.name:<40} {w_np.min():>10.4f} {w_np.max():>10.4f} "
                  f"{abs(w_np).max():>10.4f}{flag}")

# ═══════════════════════════════════════════════════════════════════════════
# STEP 9: VERIFY INT8 ACCURACY + SCALE FACTORS
# ═══════════════════════════════════════════════════════════════════════════
print("=" * 70)
print("STEP 9: VERIFY INT8 MODEL + SCALE FACTORS")
print("=" * 70)

interpreter = tf.lite.Interpreter(model_path=tflite_path)
interpreter.allocate_tensors()

input_details  = interpreter.get_input_details()
output_details = interpreter.get_output_details()

inp_detail = input_details[0]
inp_scale  = float(inp_detail['quantization_parameters']['scales'][0])
inp_zp     = int(inp_detail['quantization_parameters']['zero_points'][0])

print(f"\n📥 Input tensor:")
print(f"   Shape      : {inp_detail['shape']}")
print(f"   Dtype      : {inp_detail['dtype']}")
print(f"   Scale      : {inp_scale:.8f}")
print(f"   Zero point : {inp_zp}")

print(f"\n🔢 Quantization details:")
print(f"{'Index':>5}  {'Name':<45}  {'Dtype':<8}  {'Scale / Info'}")
print("-" * 90)

all_details = interpreter.get_tensor_details()
for t in all_details:
    qp = t['quantization_parameters']
    if len(qp['scales']) == 0:
        continue
    scales = qp['scales']
    zps    = qp['zero_points']
    if len(scales) == 1:
        scale_str = f"scale={scales[0]:.8f}, zp={zps[0]}"
    else:
        scale_str = f"per-channel {len(scales)} ch, scale[0]={scales[0]:.8f}"
    print(f"{t['index']:>5}  {t['name']:<45}  {str(t['dtype']):<8}  {scale_str}")

# Accuracy evaluation
print(f"\n📊 Đánh giá accuracy INT8 model...")
N_EVAL = min(len(X_test), 500)
correct = 0

out_zp = int(output_details[0]['quantization_parameters']['zero_points'][0])

for i in range(N_EVAL):
    sample = X_test[i:i+1].astype(np.float32)
    sample_int8 = np.round(sample / inp_scale + inp_zp).clip(-128, 127).astype(np.int8)

    interpreter.set_tensor(input_details[0]['index'], sample_int8)
    interpreter.invoke()
    output = interpreter.get_tensor(output_details[0]['index'])

    pred = 1 if int(output[0][0]) > out_zp else 0
    if pred == y_test[i]:
        correct += 1

int8_acc = correct / N_EVAL * 100

print(f"\n{'Model':<30} {'Accuracy':>10}")
print("-" * 42)
print(f"{'Float32 base model':<30} {base_acc*100:>9.2f}%")
if QAT_AVAILABLE:
    print(f"{'QAT model (fake-quant)':<30} {qat_acc*100:>9.2f}%")
print(f"{'INT8 TFLite (ASIC target)':<30} {int8_acc:>9.2f}%")
print(f"{'Accuracy drop vs float32':<30} {(base_acc*100 - int8_acc):>+9.2f}%")

if base_acc*100 - int8_acc < 2.0:
    print(f"\n✅ Accuracy drop < 2% — ĐẠT yêu cầu ASIC deployment")
else:
    print(f"\n⚠️  Accuracy drop > 2% — Xem xét tăng QAT epochs hoặc kiểm tra data")

# ═══════════════════════════════════════════════════════════════════════════
# STEP 11: TRAINING REPORT + BIỂU ĐỒ
# ═══════════════════════════════════════════════════════════════════════════
print("=" * 70)
print("STEP 11: TRAINING REPORT")
print("=" * 70)

print("\n📋 Layer-by-layer architecture:")
print(f"{'#':<3}  {'Layer':<30}  {'Output shape':<20}  {'Params':>8}")
print("-" * 70)
for idx, layer in enumerate(base_model.layers):
    try:
        out_shape = str(layer.output_shape[1:])
    except Exception:
        out_shape = "N/A"
    n_params = layer.count_params()
    print(f"{idx:<3}  {layer.name:<30}  {out_shape:<20}  {n_params:>8,}")

def last(hist, key):
    return hist.history[key][-1]

print(f"\n{'─'*50}")
print(f"FINAL RESULTS SUMMARY")
print(f"{'─'*50}")

print(f"\n[Base Model — Float32]")
print(f"  Train accuracy : {last(history_base,'accuracy')*100:.2f}%")
print(f"  Val accuracy   : {last(history_base,'val_accuracy')*100:.2f}%")

if QAT_AVAILABLE:
    print(f"\n[QAT Model — Fake-Quant]")
    print(f"  Train accuracy : {last(history_qat,'accuracy')*100:.2f}%")
    print(f"  Val accuracy   : {last(history_qat,'val_accuracy')*100:.2f}%")

print(f"\n[INT8 TFLite — ASIC Target]")
print(f"  INT8 accuracy  : {int8_acc:.2f}%")
print(f"  Model size     : {len(tflite_model)/1024:.1f} KB")

# Biểu đồ
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("ASIC Driver Drowsiness — Training History", fontsize=14)

ax = axes[0]
ax.plot(history_base.history['accuracy'],     label='Base Train', color='steelblue')
ax.plot(history_base.history['val_accuracy'], label='Base Val',   color='steelblue', linestyle='--')
if QAT_AVAILABLE:
    offset = len(history_base.history['accuracy'])
    epochs_qat = range(offset, offset + len(history_qat.history['accuracy']))
    ax.plot(epochs_qat, history_qat.history['accuracy'],     label='QAT Train', color='darkorange')
    ax.plot(epochs_qat, history_qat.history['val_accuracy'], label='QAT Val',   color='darkorange', linestyle='--')
    ax.axvline(x=offset, color='gray', linestyle=':', alpha=0.7, label='QAT start')
ax.axhline(y=int8_acc/100, color='green', linestyle=':', alpha=0.8, label=f'INT8 ({int8_acc:.1f}%)')
ax.set_xlabel('Epoch'); ax.set_ylabel('Accuracy')
ax.set_title('Accuracy (Base → QAT → INT8)')
ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

ax = axes[1]
ax.plot(history_base.history['loss'],     label='Base Train', color='steelblue')
ax.plot(history_base.history['val_loss'], label='Base Val',   color='steelblue', linestyle='--')
if QAT_AVAILABLE:
    ax.plot(epochs_qat, history_qat.history['loss'],     label='QAT Train', color='darkorange')
    ax.plot(epochs_qat, history_qat.history['val_loss'], label='QAT Val',   color='darkorange', linestyle='--')
    ax.axvline(x=offset, color='gray', linestyle=':', alpha=0.7, label='QAT start')
ax.set_xlabel('Epoch'); ax.set_ylabel('Loss')
ax.set_title('Loss (Base → QAT)')
ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_PATH, 'training_history.png'), dpi=150)
plt.show()
print("📊 Biểu đồ đã lưu: training_history.png")

print("\n" + "=" * 70)
print("✅ COMPLETE QAT PIPELINE HOÀN THÀNH!")
print("=" * 70)
print(f"📁 Output files: {OUTPUT_PATH}")
print(f"  • base_weights.weights.h5")
if QAT_AVAILABLE:
    print(f"  • qat_weights.weights.h5")
print(f"  • drowsiness_asic_int8.tflite")
print(f"  • asic_weights.h")
print(f"  • training_history.png")

# ═══════════════════════════════════════════════════════════════════════════
# STEP 11: TRAINING REPORT + BIỂU ĐỒ
# ═══════════════════════════════════════════════════════════════════════════
print("=" * 70)
print("STEP 11: TRAINING REPORT")
print("=" * 70)

print("\n📋 Layer-by-layer architecture:")
print(f"{'#':<3}  {'Layer':<30}  {'Output shape':<20}  {'Params':>8}")
print("-" * 70)
for idx, layer in enumerate(base_model.layers):
    try:
        out_shape = str(layer.output_shape[1:])
    except Exception:
        out_shape = "N/A"
    n_params = layer.count_params()
    print(f"{idx:<3}  {layer.name:<30}  {out_shape:<20}  {n_params:>8,}")

def last(hist, key):
    return hist.history[key][-1]

print(f"\n{'─'*50}")
print(f"FINAL RESULTS SUMMARY")
print(f"{'─'*50}")

print(f"\n[Base Model — Float32]")
print(f"  Train accuracy : {last(history_base,'accuracy')*100:.2f}%")
print(f"  Val accuracy   : {last(history_base,'val_accuracy')*100:.2f}%")

if QAT_AVAILABLE:
    print(f"\n[QAT Model — Fake-Quant]")
    print(f"  Train accuracy : {last(history_qat,'accuracy')*100:.2f}%")
    print(f"  Val accuracy   : {last(history_qat,'val_accuracy')*100:.2f}%")

print(f"\n[INT8 TFLite — ASIC Target]")
print(f"  INT8 accuracy  : {int8_acc:.2f}%")
print(f"  Model size     : {len(tflite_model)/1024:.1f} KB")

# Biểu đồ
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("ASIC Driver Drowsiness — Training History", fontsize=14)

ax = axes[0]
ax.plot(history_base.history['accuracy'],     label='Base Train', color='steelblue')
ax.plot(history_base.history['val_accuracy'], label='Base Val',   color='steelblue', linestyle='--')
if QAT_AVAILABLE:
    offset = len(history_base.history['accuracy'])
    epochs_qat = range(offset, offset + len(history_qat.history['accuracy']))
    ax.plot(epochs_qat, history_qat.history['accuracy'],     label='QAT Train', color='darkorange')
    ax.plot(epochs_qat, history_qat.history['val_accuracy'], label='QAT Val',   color='darkorange', linestyle='--')
    ax.axvline(x=offset, color='gray', linestyle=':', alpha=0.7, label='QAT start')
ax.axhline(y=int8_acc/100, color='green', linestyle=':', alpha=0.8, label=f'INT8 ({int8_acc:.1f}%)')
ax.set_xlabel('Epoch'); ax.set_ylabel('Accuracy')
ax.set_title('Accuracy (Base → QAT → INT8)')
ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

ax = axes[1]
ax.plot(history_base.history['loss'],     label='Base Train', color='steelblue')
ax.plot(history_base.history['val_loss'], label='Base Val',   color='steelblue', linestyle='--')
if QAT_AVAILABLE:
    ax.plot(epochs_qat, history_qat.history['loss'],     label='QAT Train', color='darkorange')
    ax.plot(epochs_qat, history_qat.history['val_loss'], label='QAT Val',   color='darkorange', linestyle='--')
    ax.axvline(x=offset, color='gray', linestyle=':', alpha=0.7, label='QAT start')
ax.set_xlabel('Epoch'); ax.set_ylabel('Loss')
ax.set_title('Loss (Base → QAT)')
ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_PATH, 'training_history.png'), dpi=150)
plt.show()
print("📊 Biểu đồ đã lưu: training_history.png")

print("\n" + "=" * 70)
print("✅ COMPLETE QAT PIPELINE HOÀN THÀNH!")
print("=" * 70)
print(f"📁 Output files: {OUTPUT_PATH}")
print(f"  • base_weights.weights.h5")
if QAT_AVAILABLE:
    print(f"  • qat_weights.weights.h5")
print(f"  • drowsiness_asic_int8.tflite")
print(f"  • asic_weights.h")
print(f"  • training_history.png")